### ISSUE TITLE
Parsley and Browserify

### ISSUE THREAD

**Issue by heltonvalentini** [guillaumepotier/Parsley.js#617]
Trying to use Parsley and Browserify but Parsley ca't be loaded.

Simple test:
```npm install parsleyjs --save```

main.js
```var parsley = require('parsleyjs');```

Run browserify( v3.32.1 )
```browserify main.js > bundle.js```

Error:
```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:88:37
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by marcandre** [comment]
No news is (probably) good news.
